#! /bin/bash

# Get first command line argument
COMMAND="$1"
DIR_OF_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case "$COMMAND" in
  ""|"l") # list
    CONTEXT_MARKERS=$(bash "$DIR_OF_SCRIPT/list_context_files.sh" show_context)

    if [ -z "$CONTEXT_MARKERS" ]; then
      echo "No context files found."
    else
      echo "$CONTEXT_MARKERS"
    fi
    ;;
  "c") # open
    FILES=$(bash "$DIR_OF_SCRIPT/list_context_files.sh")

    # remove lines containing "IMPORTANT CONTEXT" in each file in $FILES
    echo "$FILES" | xargs sed -i "" "/^.*IMPORTANT CONTEXT.*$/d"
    ;;
  # "o") # open
  #   echo "$FILES" | fzf | xargs -I {} vim {}
  #   ;;
  "g"|"gc") # context
    CONTEXT_TYPE="$2"
    TASK="$3"

    FILES=""

    if [ "${CONTEXT_TYPE#*"m"}" != "$CONTEXT_TYPE" ]; then
      # CONTEXT_TYPE includes the letter m (for marked context)
      FILES=$(bash "$DIR_OF_SCRIPT/list_context_files.sh")
    fi

    if [ "${CONTEXT_TYPE#*"a"}" != "$CONTEXT_TYPE" ]; then
      # CONTEXT_TYPE includes the letter a (for auto context)
      FILES=$(echo "$FILES"; ruby "$DIR_OF_SCRIPT/auto_context.rb" "$TASK")
      FILES=$(echo "$FILES" | sort | uniq)
    fi

    if [ -z "$FILES" ]; then
      echo "No context files found."
    fi

    SNIPPETS=$(echo "$FILES" | xargs ruby "$DIR_OF_SCRIPT/extract_context.rb")

    OUTPUT=$(
      echo "Given the following code snippets from a ${CCM_PROJECT_DESCRIPTION}, suggest changes to accomplish the following task in a well structured and high quality manner. Paying attention to the context marked IMPORTANT CONTEXT. Output only a very brief explanation and the relevant code snippets. Don't output the entire files, just the relevant code snippets."
      echo
      echo "Task: $TASK"
      echo
      echo "Files:"
      echo "$SNIPPETS"
    )

    if [ "$COMMAND" = "gc" ]; then
      echo "$OUTPUT" | pbcopy
      echo "Output copied to clipboard"
    else
      echo "$OUTPUT"
    fi
    ;;
  *)
    echo "Unknown command: $COMMAND"
    ;;
esac
