#! /bin/bash

DIR_OF_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR_OF_SCRIPT"

# capture the standard input to this script
STD_INPUT=$(cat)

ruby run_model.rb "$1" "$2" "$3$STD_INPUT"
